name: Terraform Lint

on:
  push:

jobs:
  tflint:
    runs-on: ubuntu-latest
    container:
      image: wata727/tflint:latest

    steps:
    - name: Run tflint
      run: find . -name "*.tf" -exec dirname "{}" ";" | sort | uniq | xargs tflint
