name: CI Pipeline

on:
  push:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: init
      uses: ./.github/workflows/ci/init
    - name: lint
      uses: ./.github/workflows/ci/lint
