name: Terraform Lint

on:
  push:

jobs:
  tflint:
    runs-on: ubuntu-latest
    container:
      image: wata727/tflint:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tflint
        run: find . -name "*.tf" -exec dirname "{}" ";" | uniq | xargs tflint
